baseURL: 'http://ikefumy.github.io/'
languageCode: 'en-us'
title: "ikefumy's memo"
theme: 'hugo-theme-stack'
security:
  exec:
    allow: "asciidoctor$"
  
params:
  article:
    toc: true
  sidebar:
    avatar:
      enabled: true